### ISSUE TITLE
JS/CSS files not loaded on JBoss

### ISSUE THREAD

**Issue by glucazeau** [ist-dresden/composum#9]
Hello,

I have installed Sling 7 webapp on JBoss EAP 6.4.0
I've deployed Composum 1.3.0 but when I go to this page: http://192.168.75.201:8080/sling/bin/browser.html

I see only HTML elements (forms), but JS and CSS files are not loaded. In the Sling logs I see this error:

`03.12.2015 15:12:39.127 *INFO* [http-/0.0.0.0:8080-2] logs/request.log 03/Dec/2015:15:12:39 +0100 [1652] -> GET /sling/bin/browser.html HTTP/1.1
03.12.2015 15:12:39.146 *ERROR* [10.129.201.66 [1449151959129] GET /sling/bin/browser.html HTTP/1.1] org.apache.sling.scripting.jsp.jasper.runtime.JspFactoryImpl Exception initializing page context
java.lang.IllegalStateException: JBWEB000043: Cannot create a session after the response has been committed
	at org.apache.catalina.connector.Request.doGetSession(Request.java:2649)
	at org.apache.catalina.connector.Request.getSession(Request.java:2382)
	at org.apache.catalina.connector.RequestFacade.getSession(RequestFacade.java:791)
	at org.apache.catalina.connector.RequestFacade.getSession(RequestFacade.java:801)`

How can I fix this issue? I've tried version 1.3.1 but it doesn't start because of a wrong bundle version:
`missing requirement [121.1] osgi.wiring.package; (&(osgi.wiring.package=org.osgi.framework)(version>=1.8.0)(!(version>=2.0.0)))`

Thank you

**Comment by ist-rw** [comment]
The new Bugfix Release 1.3.2 should solve the bundle version problem. The other problem is mostly a result of insufficient permissions of the current user (of the anonymous user); to handle this a check is added and delivered with release 1.3.2 which displays a simple login form if the initialization is not done properly. To use the console app read access to the paths '/libs/composum' and '/libs/jslibs' is needed.

**Comment by ist-rw** [comment]
@glucazeau Are the changes with release 1.3.2 solving your problem or is there anything open?

**Comment by glucazeau** [comment]
Hello,

Sorry I've tested quickly and didn't respond immediately.

No it doesn't seem to solve my problem. First, the login form action is "/j_security_check" so it's missing the context name. 

I've edited the source to add "/sling" and when submitting the form with admin credentials (default from Sling install) I'm redirected to "http://localhost:8080/sling/index.html/" with a 403 error. If I go to browser.html again I briefly see the page without assets and then I'm redirected to the login form, displaying:

Console assets not accessible...
Current User: admin

Do I have to manually edit ACLs or should the admin user work already?

**Comment by glucazeau** [comment]
I also realize that using the Sling standalone launchpad I can log in and use Composum as an anonymous user. The problem only occurs with JBoss.

**Comment by ist-rw** [comment]
I think we have a general gap in our implementation - wie don't support a context path. In the JBoss context such a context path is essential and wo must solve this problem but it's a bigger change with some test effort and we take a little bit of time to do that, sorry.

**Comment by glucazeau** [comment]
Thank you for working on this issue, Composum is a very nice tool that I'd like to be able to use in JBoss. No need to be sorry about the time required to implement the changes. Unfortunately I'm too new to Sling to be able to really help I think.

**Comment by ist-rw** [comment]
@glucazeau This issue should be solved with release 1.3.3, can you recheck this?

**Comment by glucazeau** [comment]
Hello,

I was actually testing, it works well, I can access everything, anonymous or not, I don't see any issue.

Thank you very much for the quick fix, I'm very glad to have Composum on our JBoss environment :thumbsup:
